# Schema for the configuration files of the Hello module.

hello.settings:
  type: mapping
  label: 'Hello settings'
  mapping:
    message:
      type: text
      label: 'Message'
      # translatable: true
